// Generated by react-native-icons-builder v0.1.0
import React from "react";
import type { SvgProps } from "react-native-svg";

export interface IconContext {
  color?: string;
  size?: string;
  style?: SvgProps["style"];
  attr?: SvgProps;
}

export const DefaultContext: IconContext = {
  color: undefined,
  size: undefined,
  style: undefined,
  attr: undefined,
};

export const IconContext: React.Context<IconContext> = React.createContext(DefaultContext);
